### PR TITLE
ZIP 158 - feat: redesign login flow

### PR DESCRIPTION
**Pull request by aalishanjami**
[ZIP-158](https://dev.azure.com/ClearfitLLC/Unzipped/_boards/board/t/Unzipped%20Team/Issues/?workitem=158)

### CODE REVIEW

**Comment by Alien4Hire** [comment]
image
Can we change this so that character is all on 1 line?

**Comment by Alien4Hire** [comment]
As we talked about, I want this button to slide down to reveal the input fields. Currently, they are just appearing, use something like this in your css styling to give it that sliding effect

`  transform: translateY(-100%);
  transition: transform 0.3s ease;`

**Comment by Alien4Hire** [comment]
Currently, the errors are not clearing on the login page. If I type in an incorrect email or password. then leave the page and come back. On load of the page I am seeing this error message
image

**Comment by Alien4Hire** [comment]
The input is overflowing out of its container and causing me to see this yellow bar when logging in.

image

**Comment by Alien4Hire** [comment]
After clicking the login button with the incorrect email and password, it will load for a minute, but then will stop trying and gives no message to the user about what the reason was for the login not working (error messaging)

**Comment by Alien4Hire** [comment]
I can make another ticket for this, but can you look into why this keeps making calls to both the register and login page repeatedly while the app is running?
image

**Comment by Alien4Hire** [comment]
Can you add an on hover function for the login button that turns it this color? 

login button: #F4F5F8
login with google: #5C67C7

**Comment by aalishanjami** [comment]
> 


I think getting it lowercaps will leave space for very tight widths, something like that:

**Comment by Alien4Hire** [comment]
Styling is looking a lot better, I am still not able to sign in though. I am trying my login
email: jaymaynard84@gmail.com
pass: Myfirst1

but getting an error that the email and password do not match
image

**Comment by aalishanjami** [comment]
that's strange, because when I try these credentials it redirects me to login

**Pull request merged**
